---
title: "Resume"
---

# Nicholas Teff, Ph.D.
Data scientist | mathematician

nicholas.teff@gmail.com | 605-759-8112 | Iowa City, IA

## Summary

A seasoned data scientist with 10+ years of experience using Python and
SQL. At Shopify, I play a critical role in using data to drive decisions
for a lending product fully powered by deep learning. I have also
created analytics teams across industries, spoken at industry
conferences, and volunteered to guide undergraduate students in
developing practical analytics skills.

## Employment history

2021-Present **Shopify**, Senior data scientist

-   Leveraged my expertise in product analytics, analytics engineering, and machine learning to support the small business lending product, resulting in improved risk mitigation for Shopify and its external banking partners and investors. `[SQL (Trino, BigQuery), PySpark, dbt, Mode, Airflow]`

-   Successfully migrated a Spark streaming pipeline for predicting loan default likelihood to one using Flink and Kafka. `[pyspark, Flink, Kafka]`

-   Provided valuable statistical expertise for multiple A/B experiments, which led to significant improvements in the product's UX and marketing performance. `[pyspark, SQL]
`
-   Collaborated with business partners to establish new top-line
metrics and KPIs, which helped to align the lending product with Shopify's overall growth strategy.

2017-2021 **University of Iowa Center for Advancement**, Senior data
scientist

-   Led a team of data analysts to provide critical analytics and
reporting support to the organization. `[SQL (Microsoft), pandas, PowerBI, Tableau]`

-   Initiated and grew a successful revenue-generating social media
analytics program within the first 18 months of operation. `[SQL,
APIs, Google Analytics, PowerBI]`

-   Spearheaded the development and monitoring of key metrics for the Strategic Plan to increase donor retention and engagement.

-   Drove significant improvements in alumni engagement, donor identification, and campaign success through the deployment of
machine learning models, resulting in a 30% lift in email
engagement and a 15% increase in donations in A/B testing. `[SQL,
pandas, sklearn]`

2014-2017 **Transamerica**, Senior risk analyst

-   Led the creation of an inaugural predictive analytics team of 3 data analysts and interns within the actuarial department.

-   Developed and implemented machine learning models to predict
customer behavior, with one integrated into the production
actuarial platform (MG-ALFA). `[SQL (Microsoft and Oracle), pandas, sklearn, R, alteryx]`

-   Analyzed variable annuity portfolio risks and provided hedge
recommendations, including modeling stochastic simulations of
gamma and delta hedge rebalancing. `[SQL, VBA]`

-   Conducted risk reviews of risk-managed mutual funds and ETF
liquidity during market downturns, providing key insights to
executive management.

## Education

2008--2013 Ph.D., Mathematics - **University of Iowa**, *Iowa City, IA*

2006--2008 M.S., Mathematics - **University of Vermont**, *Burlington, VT*

2000--2003 B.A., Mathematics, Minor Economics - **Winona State
University**, *Winona, MN*

## Technology skills

Python (pandas, pyspark, sklearn, numpy, flask, etc...), SQL (Trino,
BigQuery, MS SQL, dbt, etc...), BI tooling (Mode, Power BI, Tableau,
Looker, Alteryx), GitHub/Git, R, Kafka, Spark, Flink, Airflow, HTML/CSS

## Miscellany

### Recognition

2021 **UICA Innovation Peer Award**

2020 **EverTrue's 40 under 40**

### Presentation

2021 **Know Your Audience: Data-Driven Personas** DRIVE/Cast, CASE.

2019 **Demystifying Machine Learning** PlugIn to Data Science, APRA.

2019 **Digital Engagement for Prospect Discovery** RAISE, EverTrue.

2018 **Portfolio Optimization** Big 10 Development Conference.

2016 **Predictive Analytics** Transamerica's Actuarial Department.

### Writing

2013 [The Hessenberg representation](http://ir.uiowa.edu/etd/4919/),
Ph.D. dissertation.

2011 [Representations on Hessenberg varieties and Young's
rule](http://www.dmtcs.org/dmtcs-ojs/index.php/proceedings/article/viewArticle/dmAO0179.html)
FPSAC 2011 proceedings, Assoc. Discrete Math. Theor. Comput. Sci.
(903-914).

### Service

2017-present **Tippie College of Business - University of Iowa**, -
Mentorship and providing hands-on experience to undergraduate students
in business analytics.

2004-2006 **AmeriCorps\*VISTA Habitat for Humanity Restore Winona**, -
Managed 3 volunteer programs that focused on salvaging, reusing, and
recycling.

### Hobbies

Father, coffee enthusiast, bread baker, gardener, car-camper, day-hiker,
board-game geek, beginner weight-lifter
